### ISSUE TITLE
Show only first N (12?) images on home page

### ISSUE THREAD

**Issue by mikekaminsky** [mikekaminsky/belair#24]
- When someone uploads an episode, updated at on the show should be updated
- Index page should return orders in updated_at order
- There should be a limit on the number of shows returned for index page

**Comment by mikekaminsky** [comment]
We currently only show the first 6 most recent shows (yay), but we should adjust the backend so we only serve the most recent 6 instead of all shows as well.

**Comment by se3000** [comment]
Sure, 6 seems low though.

**Comment by omnikrll** [comment]
Yeah right now I'm just slicing out the first 6 results in the JS
controller- the design originally showed 6 shows- but I agree that seems
low. I'm not sure if the intent in the design was to paginate the home page
or what.
