### ISSUE TITLE
Show object should have a Description property

### ISSUE THREAD

**Issue by omnikrll** [mikekaminsky/belair#3]
jus a lil string y'all

**Comment by se3000** [comment]
I'm looking at you @mikekaminsky

**Comment by mikekaminsky** [comment]
I'll claim this and the other basic CRUD features. Will work on a branch and submit a PR, hopefully this weekend :)

**Comment by mikekaminsky** [comment]
Boom? https://github.com/mikekaminsky/belair/commit/b4704984cfc3eb08a497faa80763a458ecd5a6b8

**Comment by se3000** [comment]
Boom indeed.
