### ISSUE TITLE
Figure out how to access voscast stream

### ISSUE THREAD

**Issue by se3000** [mikekaminsky/belair#4]
Maybe use [this](http://stackoverflow.com/questions/18652583/play-from-shoutcast-url-in-android).

Also check out [Voscast docs here](http://kb.voscast.com/index.php?action=artikel&cat=1&id=20&artlang=en).

**Comment by se3000** [comment]
@omnikrll @mikekaminsky did either of you get a chance to figure out the credentials? Or, will you be there again before Monday?

**Comment by mikekaminsky** [comment]
It looks like we should be able to pull this info off of our Nicecast setup? The docs [here](http://kb.voscast.com/index.php?action=artikel&cat=3&id=28&artlang=en) make it seem like we should have a dedicated server ID to use to pull the string?

Specifically, if we can figure out the servername and port number, we should be able to link to the stream [like in these docs](http://kb.voscast.com/index.php?action=artikel&cat=3&id=33&artlang=en)

**Comment by mikekaminsky** [comment]
Found it. Not su

**Comment by mikekaminsky** [comment]
Additionally, it seems like we can use [this](http://kb.voscast.com/index.php?action=artikel&cat=1&id=37&artlang=en) to tell when someone is currently broadcasting

**Comment by omnikrll** [comment]
Nice!

**Comment by se3000** [comment]
🔥🔥🔥

**Comment by mikekaminsky** [comment]
Closed by https://github.com/mikekaminsky/belair/pull/18
