### ISSUE TITLE
Should be able to switch back to live stream from archived episode

### ISSUE THREAD

**Issue by omnikrll** [mikekaminsky/belair#41]
I was listening to the live stream, browsed around for a while, and started listening to an older episode. With an archived episode playing, the only way to switch back to the live stream was to refresh the page. It would be nice to have some way to switch back over to the live stream, if there is one.

**Comment by mikekaminsky** [comment]
Yeah, Arden and I were talking about this the other day. Would be nice if there was like a little banner at the top that said 'Bel-Air on Air' (only appears when stream is active), and clicking on it would always start playing the stream. Could probably do this with all javascript using the function Steve built to detect the livestream.

**Comment by se3000** [comment]
Right now the player just tries to play the live stream and finds another
song if that doesn't work. So, the only way to check is to actually try to
play it. Definitely possible to build something else, but not with what's
in place now.

**Comment by mikekaminsky** [comment]
Aha. Nice. I looked up some stuff on how voscast recommends detecting the stream here: https://github.com/mikekaminsky/belair/issues/4

It seems reasonably straightforward to ping that server and see if the text 'Server is currently down.' appears (I think???)

**Comment by se3000** [comment]
I was seeing really strange response types before when the server is down,
possibly UDP related.

Also, when the server is up, since it's UDP-ish(streaming) the response
won't close and you'll never get a chance to parse text out of it.

There's probably something simple I'm missing, never looked at the actual
API docs.

**Comment by mikekaminsky** [comment]
I didn't look closely, but my impression was that there are two separate servers, one for streaming and one for indicating when it's up or down. That could be totally wrong tho
