### ISSUE TITLE
Should not be able to get to Admin home page without entering username / password

### ISSUE THREAD

**Issue by omnikrll** [mikekaminsky/belair#44]
At the moment you can just go straight to the admin dashboard without logging in. It'll prompt you for a username / password when you try to save anything, but I'd expect it to prompt you to login before getting to the admin dashboard at all.

**Comment by se3000** [comment]
Not sure what this is a problem, all the data is public... Just looks
crappy.

Easy fix though.

**Comment by mikekaminsky** [comment]
I don't really care either....not planning on prioritizing this

**Comment by se3000** [comment]
Was this done? It's like a 1 liner, happy to do it next time I'm in the
code base... Was just trying to point out that there's no real security
problem.

**Comment by omnikrll** [comment]
No, I just closed the ticket since it seemed like a non-issue.
