### ISSUE TITLE
[UX Audit] Stream should not be set to autoplay

### ISSUE THREAD

**Issue by binaricorn** [mikekaminsky/belair#49]
# The site should not be autoplaying the track when it loads. I talked to @omnikrll today about this and it seems like the consensus was to set it to autoplay but I think that makes for quite an unpleasant experience. In Greg's designs, the stream is paused on load.

Let me know if we should chat about this though.

**Comment by mikekaminsky** [comment]
I don't have much of a preference here. The only argument I have in favor is that auto-play makes it seem more like a radio station where you tune in and here whatever's on. The obvious counter-argument is that i too hate it when other websites auto-play.

**Comment by mikekaminsky** [comment]
Also, this depends on handling https://github.com/mikekaminsky/belair/issues/41 first. Right now there's no way to get back to the live stream without refreshing, so if we take off autoplay there won't be any way to get back to the livestream at all :0

**Comment by binaricorn** [comment]
@mikekaminsky I think we can modify the design a bit so that the top section is highlighted more, but doesn't solve issue #41 that's true. Would putting a separate "back to streaming" link next to the play button be hard to implement?

**Comment by mikekaminsky** [comment]
Not sure. The idea would be to 1) check if the stream is live and 2) if it
is, show the button. This is a bit out of my wheelhouse but I can give it a
shot this weekend.

**Comment by se3000** [comment]
I would count #41 as a separate issue. This issues seems a bit easier to me, just pause the episode... maybe detect if the live stream is available on load.

**Comment by mikekaminsky** [comment]
Good point @se3000. I'll work this weekend to fix this issue, and if I'm on a roll will try to tackle #41 as well.
